language: php

sudo: false

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6

before_script:
  - mysql -u root -e 'create database silex_mysqli_test;'
  - composer self-update
  - composer install --prefer-source

script: vendor/bin/phpunit --coverage-text
